### ISSUE TITLE
Improve Home page of auth_plug Heroku Example

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug_example#3]
At present the home page of the Heroku example: https://auth-plug-example.herokuapp.com
is just a standard phoenix App. This is not very informative/insightful as to the _purpose_ of the app:
![image](https://user-images.githubusercontent.com/194400/80794624-48bc2f80-8b92-11ea-92b2-a5eb2008bd76.png)

# Todo

+ [x] Update the [`/lib/app_web/templates/page/index.html.eex`](https://github.com/dwyl/auth_plug_example/blob/master/lib/app_web/templates/page/index.html.eex) to:
  + [x] Remove the Phoenix Logo and instead add `auth_plug` _example_
  + [x] Remove "Get Started", "Resources" and "Help" links as they aren't relevant to the example.
  + [x] Update the Copy in the "hero" section to reflect the purpose of this example app.
  + [x] Link to the **`auth_plug`** repo on GitHub in the footer
  + [x] Link to the `/admin` route _prominently_ so people know what to do next.
+ [x] Update test assertion to reflect the removal of "Welcome to Phoenix!" from the homepage:
https://github.com/dwyl/auth_plug_example/blob/a820f94d0fc98ebe65fd7900b3962004c6ebf7e6/test/app_web/controllers/page_controller_test.exs#L6
+ [x] Create Pull Request
+ [x] Confirm Heroku auto-published the new version when PR is merged. 
+ [x] Add "ping" (wake up heroku) image to `README.md` see: https://github.com/dwyl/ping

**Comment by nelsonic** [comment]
Inform people that they will be redirected to the auth app:
![image](https://user-images.githubusercontent.com/194400/87544389-41d79000-c69e-11ea-918a-f25189552965.png)

**Comment by SimonLab** [comment]
Trying to run the project locally returns an error:
![image](https://user-images.githubusercontent.com/6057298/136536174-0b1fe3a4-dcd8-4edc-87a7-1db01fe188c5.png)

:eyes:

**Comment by SimonLab** [comment]
This is now deployed on Heroku:
![image](https://user-images.githubusercontent.com/6057298/136659897-18ae2598-6fb6-4ceb-88bc-b2de591bcfa7.png)

@nelsonic I let you close this issue if you are happy with it.

**Comment by nelsonic** [comment]
@SimonLab Yeah, I think it looks _much_ better. Thanks. 🚀
