### ISSUE TITLE
Update to Latest Version of auth_plug

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug_example#4]
Given that the recent refactor of **`auth_plug`** removed a few things e.g: `AuthPlug.session_options/0` 
https://github.com/dwyl/auth_plug/pull/20/files#diff-1560d1759954bb80cc81c6769976610fL68
![image](https://user-images.githubusercontent.com/194400/87414288-79bdd500-c5c3-11ea-8a4f-bbf060525c34.png)

We need to _update_ the ***example*** App to ensure that everything still works as expected.

# Todo

+ [x] Update the version of `auth_plug` in `mix.exs` to [`1.2.0`](https://hex.pm/packages/auth_plug/1.2.0)
+ [ ] Confirm everything still works on `localhost`
+ [ ] Commit the change & Create PR
+ [ ] Confirm everything still works on Heroku

**Comment by nelsonic** [comment]
Yep, same compilation error as in https://github.com/dwyl/auth/issues/83#issuecomment-658098200 after updating to `auth_plug@1.2.0` 
which means it should probably have been released as `2.0.0` (_breaking change_). 💭 

```
Generated auth_plug app
==> app
Compiling 14 files (.ex)

== Compilation error in file lib/app_web/endpoint.ex ==
** (UndefinedFunctionError) function AuthPlug.session_options/0 is undefined or private
    AuthPlug.session_options()
    lib/app_web/endpoint.ex:45: (module)
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by nelsonic** [comment]
After removing the call to `AuthPlug.session_options/0` from `endpoint.ex`:
https://github.com/dwyl/auth_plug_example/blob/a820f94d0fc98ebe65fd7900b3962004c6ebf7e6/lib/app_web/endpoint.ex#L45

It now works again. 👍

**Comment by nelsonic** [comment]
Example working on `localhost`:
![image](https://user-images.githubusercontent.com/194400/87435409-9ec24000-c5e3-11ea-8433-4fc5f3039820.png)
