### ISSUE TITLE
Chore: Migrate demo app from Heroku to Fly.io

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug_example#45]
In light of Heroku discontinuing "hobby" apps https://github.com/dwyl/learn-heroku/issues/52
We are migrating our apps off Heroku to Fly.io

# Todo

+ [x] Create new `org` for the demo app on Fly.io
+ [x] Create new `app` 
+ [x] Deploy the app using `fly launch`
+ [x] Update the docs in the `README.md`

Estimating **`T25m`** because I've already done this a couple of times, see: https://github.com/dwyl/phoenix-chat-example/issues/122

**Comment by nelsonic** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/194400/202491060-6c2d015b-1313-4f94-8a8c-cdb52bd8aa5f.png">


https://auth-plug.fly.dev/admin
![image](https://user-images.githubusercontent.com/194400/202489177-47c53d17-d4e4-44eb-a923-c64e14ad214c.png)


![image](https://user-images.githubusercontent.com/194400/202489883-16d727f4-8f18-4fba-9e27-00ea01329482.png)
