### ISSUE TITLE
Add Coverage Checking to CI to Mitigate Regressions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug_example#5]
At present this project does not have Coverage enabled because it's so simple.
But it means we don't know what code is being executed/tested. 😞 

# Todo

+ [x] add `excoveralls` to `mix.exs` so that we can check test coverage.
+ [x] add codecov bash script invocation to `.travis.yml` e.g:
```
after_success:
  - bash <(curl -s https://codecov.io/bash)
```
+ [x] run the `MIX_ENV=test mix coveralls.html`
+ [x] open the resulting file: `open cover/excoveralls.html`
+ [x] write any necessary tests to make sure all code is executed **or** ignore boilerplate code in `coveralls.json` file.
+ [ ] Create and assign PR once **100%** coverage achieved.
+ [ ] Add Travis-CI and Codecov badges to `README.md`

```
<div align="center">

# `auth_plug` _example_

A working example of `auth_plug` showing you how simple it is to add to add `auth` to your Phoenix App!

[![Build Status](https://img.shields.io/travis/dwyl/auth_plug/master.svg?style=flat-square)](https://travis-ci.org/dwyl/auth_plug)
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/auth_plug/master.svg?style=flat-square)](http://codecov.io/github/dwyl/auth_plug?branch=master)
[![Hex.pm](https://img.shields.io/hexpm/v/auth_plug?color=brightgreen&style=flat-square)](https://hex.pm/packages/auth_plug)
[![Libraries.io dependency status](https://img.shields.io/librariesio/release/hex/auth_plug?logoColor=brightgreen&style=flat-square)](https://github.com/dwyl/auth_plug/blob/master/mix.exs)
[![HitCount](http://hits.dwyl.com/dwyl/auth_plug.svg)](http://hits.dwyl.com/dwyl/auth_plug)
</div>
<br />
```
**Note**: replace `auth_plug` with `auth_plug_example` in all the badges.
